# Generated by Django 2.1.5 on 2019-01-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190121_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.Category', verbose_name='Категория'),
        ),
    ]
