# Generated by Django 2.1.5 on 2019-01-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190121_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank='True', upload_to='media/images', verbose_name='default.png'),
        ),
    ]
