# Generated by Django 2.1.5 on 2019-01-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank='True', upload_to='article_<django.db.models.fields.AutoField>', verbose_name='default.png'),
        ),
    ]
