# Generated by Django 2.1.5 on 2019-01-22 15:20

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190122_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='default.png'),
        ),
    ]
