# Generated by Django 2.1.5 on 2019-01-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190122_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visits',
            field=models.IntegerField(default=0, editable='False', verbose_name='Посещений'),
        ),
    ]
