# Generated by Django 2.1.5 on 2019-01-22 19:33

import blog.models
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_article_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=froala_editor.fields.FroalaField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='Заглавная картинка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
