# Generated by Django 2.1.5 on 2019-01-22 22:04

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190123_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=froala_editor.fields.FroalaField(default=''),
            preserve_default=False,
        ),
    ]
