# Generated by Django 2.1.5 on 2019-01-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.TextField(default='', verbose_name='Предпросмотр текста'),
            preserve_default=False,
        ),
    ]
