# Generated by Django 2.1.5 on 2019-01-23 00:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_article_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_image_1',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='Предпросмотр 1'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_image_2',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='Предпросмотр 2'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_image_3',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='Предпросмотр 3'),
        ),
    ]
