# Generated by Django 2.1.5 on 2019-01-23 00:45

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190123_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_image_4',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='Предпросмотр 4'),
        ),
    ]
