# Generated by Django 2.1.5 on 2019-01-23 11:51

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_article_preview_image_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cover cropping'),
        ),
    ]
