# Generated by Django 2.1.5 on 2019-01-23 11:59

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_article_cover_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_image_1_cropping',
            field=image_cropping.fields.ImageRatioField('preview_image_1', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='preview image 1 cropping'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_cropping',
            field=image_cropping.fields.ImageRatioField('cover_image', '1252x754', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cover cropping'),
        ),
    ]
