# Generated by Django 2.1.5 on 2019-01-23 13:06

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190123_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='Заглавная картинка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_image_1',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='Предпросмотр 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_image_2',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='Предпросмотр 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_image_3',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='Предпросмотр 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_image_4',
            field=models.ImageField(blank='True', upload_to=blog.models.Article.get_upload_path, verbose_name='Предпросмотр 4'),
        ),
    ]
