# Generated by Django 2.1.5 on 2019-01-26 09:08

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20190123_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_image_4_cropping',
            field=image_cropping.fields.ImageRatioField('preview_image_4', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='preview image 4 cropping'),
        ),
    ]
